apiVersion: apps/v1
kind: Deployment
metadata:
  name: zdt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zdt
  template:
    metadata:
      labels:
        app: zdt
    spec:
      containers:
      - name: zdt
        image: zdt:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        - containerPort: 50051
        env:
        - name: DB_PATH
          value: "/data/database.db"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: zdt-pvc
